site_name: ColorJS
pages:
    - 'Introduction': 'index.md'
    - 'Installation': 'installation.md'
    - 'Créer une présentation': 'creer.md'
    - 'Présenter votre travail': 'presentation.md'
theme:
  name: 'readthedocs'
